feat(python): add ast-based helpers for loops
freeCodeCamp/curriculum-helpers pull request #149
Opened 2024-02-16 16:46 UTC by Dario-DC

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

2024-02-23 16:36 UTC, ojeytonwilliams requested changes
These are looking great, @Dario-DC, just some small issues.

Also, if you're happy with the suggestions, could you add the new features to the docs?

2024-02-23 16:36 UTC, ojeytonwilliams commented on python/py_helpers.test.py
> +        self.assertIsNone(node.find_whiles()[0].find_while_conditions()[1].tree)
```suggestion
        self.assertTrue(node.find_whiles()[0].find_while_conditions()[0].is_equivalent("x > 0"))
        self.assertIsNone(node.find_whiles()[0].find_while_conditions()[1].tree)
```
I think that's what you're generally going to be using this for, so a test would be nice.

2024-02-23 16:36 UTC, ojeytonwilliams commented on python/py_helpers.py
> +                return if_statement
```suggestion
                return if_statement
        return Node()
```
Implicitly returning `None` breaks the chain and continued chaining gives you `AttributeError: 'NoneType' object has no attribute...` errors.

2024-02-23 16:36 UTC, ojeytonwilliams commented on python/py_helpers.py
> +                return while_loop
```suggestion
                return while_loop
        return Node()
```

2024-02-23 16:36 UTC, ojeytonwilliams commented on python/py_helpers.py
> +                return for_loop
```suggestion
                return for_loop
        return Node()
```

2024-02-24 07:01 UTC, Dario-DC commented
> Also, if you're happy with the suggestions, could you add the new features to the docs?

Sure, I'm going to do add them to the docs @ojeytonwilliams

2024-02-28 14:30 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

Thanks again, @Dario-DC. I'm very happy to get these in.

2024-02-28 14:30 UTC, merged