feat: permutateRegex
freeCodeCamp/curriculum-helpers pull request #156
Opened 2024-02-26 11:56 UTC by gikf

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

- - -
- Helper dealing with regex that should allow specific parts in any order. Ie. for regex composed from parts `a`, `b` and `c`, it should match both `a || b || c` and `b || a || c`, and any other permutation.
- Name is a bit rough.
- Default `elementsSeparator` is a bit arbitrarily picked...
- A bit of context https://github.com/freeCodeCamp/freeCodeCamp/pull/53606#issuecomment-1960408047

Capturing groups in individual regex
- It's rather easy to think of situation where it might be handy - ie. `("|')thing\1`, `(?<m>"|")thing\k<m>`. It'd be good to support it.
- If individual regex has capturing group, it will likely break. Named capturing group will surely break - group names have to be unique. Reference to non-named capturing group will reference to the same capturing group from every permutation, so that most likely will also not work as intended.
- What comes to mind is replacing the group reference or name when joining permutations, to ensure their uniqueness and that reference is to the right thing. In such case expecting the capturing group to be named named would make it much easier, than finding/replacing unnamed groups and their numbered references.
- Any ideas?

2024-02-28 04:47 UTC, naomi-lgbt commented
Yes this would be so helpful for saving me on some of the regex I've written.

2024-02-28 09:45 UTC, ojeytonwilliams requested changes
Thanks, @gikf, this looks really useful!

2024-02-28 09:45 UTC, ojeytonwilliams commented on docs/curriculum-helpers.md
> +permutateRegex([source1, regex1, source2]).source === new RegExp(/(?:titleInput\.value\s*(?:!==|!=)\s*currentTask\.title\s*\|\|\s*dateInput\.value\s*(?:!==|!=)\s*currentTask\.date\s*\|\|\s*descriptio
How about smaller sources? It's quite tricky to see what the functions actually doing with these. Unless I'm missing something `permutateRegex(['a', \b\, 'c'])` should capture everything we care about.

Also, could you document the separator? It wasn't obvious to me what that did until I looked into the source.

2024-02-28 09:45 UTC, ojeytonwilliams commented on lib/__tests__/curriculum-helper.test.ts
> +    expect(regex.source).not.toEqual("(?:)");
```suggestion
```
Do we need this? The next test checks what it doesn't match, after all.

2024-02-28 09:45 UTC, ojeytonwilliams commented on lib/__tests__/curriculum-helper.test.ts
> +    console.log(regex);
```suggestion
```

2024-02-28 09:45 UTC, ojeytonwilliams commented on lib/index.ts
> +  function permute(array: (string | RegExp)[], length: number) {
```suggestion
  // Heap's algorithm
  function permute(array: (string | RegExp)[], length: number) {
```
Just so people know what they're looking at.

2025-03-14 18:40 UTC, gikf commented
@ojeytonwilliams sorry, I had it tucked away in parts of mind that I avoided a bit.

Review suggestions were implemented. I've added ability to use named capture groups within permutated inputs.

2025-03-17 09:43 UTC, ojeytonwilliams submitted a review, later dismissed
Thanks for revisiting this, @gikf. LGTM :+1:

2025-03-17 09:55 UTC, ojeytonwilliams approved these changes

2025-03-17 09:55 UTC, merged