feat: create a JS helpers class
freeCodeCamp/curriculum-helpers pull request #190
Opened 2024-04-08 18:43 UTC by a2937

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

In my opinion, it does come up fairly often that we use regex to ensure that variables are actually present in functions with default values; and I think the potential spacing issues aren't generally worth with it when we can just manually extract them. 

I also tried to do some house-keeping and hopefully keep eslint from reformatting the fixtures as it is very space sensitive. As I use Visual Studio to edit Typescript, I also added some of the contents of VisualStudio.gitignore to the local gitignore. I will be be happy to remove the unrelated content and discuss them at a later date.

2024-04-08 20:09 UTC, naomi-lgbt requested changes
The first thing that stands out is that this would break for valid single-parameter syntax:

```js
const myFunc = name => console.log("Name");
```

2024-04-08 20:09 UTC, naomi-lgbt commented on .gitignore
These changes should probably be made in a separate PR - if VSCode is generating these files for some contributors, we likely don't want them.

2024-04-08 20:43 UTC, a2937 commented on .gitignore
I figured as much. I'll remove those changes from this PR.

2024-04-08 23:24 UTC, a2937 commented
Did I get it Naomi?

2024-04-16 07:34 UTC, ojeytonwilliams requested changes
Hi @a2937, thanks for putting this together. The code looks like it does the job well, thanks. The only issue is that it's a little hard to read, so I made some suggestions for how that could be improved:

2024-04-16 07:34 UTC, ojeytonwilliams commented on lib/index.ts
> +export class JSHelpers {
Since we have no state in this class, I think it's fine to simply export the `getFunctionArgs` function on its own.

2024-04-16 07:34 UTC, ojeytonwilliams commented on lib/index.ts
> +      /(?:function\s*[^(]*\(([^)]*)\))|(?:\(([^)]*)\)\s*=>)|(?:\b(?:const|let|var)\s*\w+\s*=\s*function\s*\(([^)]*)\))| =\s+([^)]*)=>/;
This is a little tricky to read. Could you split the regex up slightly so it's clearer which part does what?

2024-04-16 07:34 UTC, ojeytonwilliams commented on lib/__fixtures__/curriculum-helpers-javascript.ts
> +const codeString4 = `const myFunc = name => console.log("Name")`;
These names are quite generic. Ideally they should describe the string. For example `codeString1` could be `functionDeclaration`.

2024-04-16 07:34 UTC, ojeytonwilliams commented on lib/__tests__/javascript-helper.test.ts
> +    it("function", function () {
This is also a little generic. Ideally the whole test should be make a meaningful sentence. E.g. `it('gets arguments from function declarations')`.

2024-04-16 07:34 UTC, ojeytonwilliams commented on lib/index.ts
> +  getFunctionArgs(code: string) {
```suggestion
  getFunctionParams(code: string) {
```
Nit: it gets params, so the name should reflect that.

2024-04-16 16:04 UTC, a2937 commented on lib/__fixtures__/curriculum-helpers-javascript.ts
> +const codeString4 = `const myFunc = name => console.log("Name")`;
Happily renamed those variables. I will need to remember to make sure to add something so my Visual Studio Code instance doesn't try to reformat that file though.

2024-04-16 16:04 UTC, a2937 commented on lib/__tests__/javascript-helper.test.ts
> +    it("function", function () {
Test cases have been renamed.

2024-04-16 16:04 UTC, a2937 commented on lib/index.ts
> +  getFunctionArgs(code: string) {
The name has been fixed..

2024-04-16 16:05 UTC, a2937 commented on lib/index.ts
> +      /(?:function\s*[^(]*\(([^)]*)\))|(?:\(([^)]*)\)\s*=>)|(?:\b(?:const|let|var)\s*\w+\s*=\s*function\s*\(([^)]*)\))| =\s+([^)]*)=>/;
It has been split and should be way more maintainable now.

2024-04-16 16:06 UTC, a2937 commented on lib/index.ts
> +export class JSHelpers {
It has been moved into its own exported function for now.

2024-04-16 16:26 UTC, ojeytonwilliams commented on lib/__fixtures__/curriculum-helpers-javascript.ts
> +const codeString4 = `const myFunc = name => console.log("Name")`;
Yeah, that was a pain for far too long. https://github.com/freeCodeCamp/curriculum-helpers/pull/191 *should* have fixed it, though.

2024-04-16 16:28 UTC, ojeytonwilliams approved these changes
This looks great. Thanks @a2937!

@naomi-lgbt If you're happy, merge away.

2024-04-16 16:33 UTC, naomi-lgbt approved these changes
Ship it

2024-04-16 16:34 UTC, merged