fix: script imports for tpescript
freeCodeCamp/curriculum-helpers pull request #46
Opened 2022-08-30 11:42 UTC by Sembauke

2022-09-05 16:42 UTC, Nirajn2311 approved these changes

2022-09-06 11:06 UTC, ojeytonwilliams commented
Could you elaborate a bit on the purpose of these changes?  For the most part it looks like they should be changes to strip-comments, rather than this repo.

2022-09-06 11:36 UTC, Sembauke commented
> 



> Could you elaborate a bit on the purpose of these changes? For the most part it looks like they should be changes to strip-comments, rather than this repo.

It wouldn't make much sense to keep strip-comments in it's own repo, it is only used with the curriculum helpers.  We also wanted to convert it from a commonJS module to a ECMA module so that it could be easily implemented with script imports without doing a lot of fancy typescript configurations.

2022-09-07 16:04 UTC, Sembauke commented
Hi @ojeytonwilliams 
I agree we should not leave out the extra users of the strip-comments library. But I think this is the way to go for the short term. Let's open an issue for it on the strip comments library when this is merged in.

2022-09-07 16:11 UTC, Sembauke commented
Babel is still needed to run Jest with ESM modules.

2022-09-07 17:07 UTC, ojeytonwilliams commented
> Babel is still needed to run Jest with ESM modules.

Ah, right, I completely missed that.  Thanks!

2022-09-08 10:24 UTC, ojeytonwilliams requested changes
This is looking good.  I just found a few minor things here and there:

2022-09-08 10:24 UTC, ojeytonwilliams commented on .babelrc
> +  //"plugins": ["babel-plugin-add-import-extension"]
```suggestion
  ]
```

2022-09-08 10:24 UTC, ojeytonwilliams commented on lib/index.ts
> +    return strip(codeStr, {});
```suggestion
    return strip(codeStr);
```
I don't think we should be changing the strip api. Let's keep the options optional.

2022-09-08 10:24 UTC, ojeytonwilliams commented on .babelrc
> +  //"plugins": ["babel-plugin-add-import-extension"]
```suggestion
  ]
```

2022-09-08 10:24 UTC, ojeytonwilliams commented on lib/strip.ts
> +export const strip = ((input, options) => {
```suggestion
export const strip = ((input, options?) => {
```

2022-09-08 10:24 UTC, ojeytonwilliams commented on lib/strip.ts
> +strip.block= (input, options)=> {
```suggestion
strip.block= (input, options?)=> {
```

2022-09-08 10:24 UTC, ojeytonwilliams commented on lib/strip.ts
> +strip.line = (input, options) => {
```suggestion
strip.line = (input, options?) => {
```

2022-09-08 10:24 UTC, ojeytonwilliams commented on lib/strip.ts
> +strip.first = (input, options) => {
```suggestion
strip.first = (input, options?) => {
```

2022-09-08 10:24 UTC, ojeytonwilliams commented on lib/parse.ts
> +export const parse = (input: string, options: Partial<options> = {}) => {
```suggestion
export const parse = (input: string, options?: Partial<options> = {}) => {
```

2022-09-08 10:30 UTC, ojeytonwilliams commented on lib/index.ts
> +  const noCommentsCallingCode = strip(callingCode, {});
```suggestion
  const noCommentsCallingCode = strip(callingCode);
```
Sorry, missed this one.

2022-09-08 10:31 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-09-08 10:35 UTC, merged