feat: add 2 CSS helper methods
freeCodeCamp/curriculum-helpers pull request #96
Opened 2023-11-17 10:52 UTC by leonfeng

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Add two new methods to the `CSSHelp` class for testing challenges where multiple CSS selectors are valid. Example: https://github.com/freeCodeCamp/freeCodeCamp/pull/52379

2023-11-20 17:50 UTC, naomi-lgbt requested changes
This will need to be updated such that the tests pass.

2023-11-21 15:56 UTC, leonfeng commented
> This will need to be updated such that the tests pass.

Finally figured it out. No idea how the tests passed on my machine before...

2023-11-23 07:11 UTC, Sembauke commented
This will require a new version of the package to be released.

2023-11-23 07:23 UTC, Sembauke approved these changes

2023-11-23 07:26 UTC, merged